### ISSUE TITLE
 mate-icon-theme/mate/scalable/places/start-here-symbolic.svg is a GNOME logo icon

### ISSUE THREAD

**Issue by darkshram** [mate-desktop/mate-icon-theme#14]
mate-icon-theme/mate/scalable/places/start-here-symbolic.svg is a GNOME logo icon instead of a MATE logo icon.

**Comment by NiceandGently** [comment]
and what's the problem, why do you use it?
.... feel free to create a mate one ;)

**Comment by darkshram** [comment]
I was looking for a symbolic icon to use on lightdm-gtk for my distro. I got an unofficial one from this patch for lightdm-gtk: https://code.launchpad.net/~profzoom/lightdm-gtk-greeter/add-mate-badge/+merge/243069
The problem of this issue is: the GNOME logo is copyright and trademark of GNOME. There shouldn't be any GNOME logo in MATE icon theme. Ask any lawyer about this issue. ;-)

**Comment by darkshram** [comment]
Posted proposed icon at http://www.alcancelibre.org/images/start-here-symbolic.svg

**Comment by NiceandGently** [comment]
link is broken

**Comment by NiceandGently** [comment]
PS:
simply remove the orign icon during package building, if you feel a lawyer struggle your neck ;)
