### ISSUE TITLE
Desktop icon text color resets after reboot.

### ISSUE THREAD

**Issue by BenFenner** [mate-desktop/mate-icon-theme#16]
**Note to mate-icon-theme team:**
After navigating a few bug reporting systems, I believe I'm at least sort of in the right place. If this belongs elsewhere, please let me know so I can report this bug in the right place.

**Subject:**
Desktop icon text color resets after reboot.

**System configuration:**
Linux Mint 17 LTS (64-bit)
Kernel Linux 3.13.0-24-generic
MATE 1.8.1

**Steps to reproduce:**
Right click open area on Desktop → Change Desktop Background → Theme → Customize
Controls → Redmond
Colors → [NONE]
Window Border → WinMe
Icons → MintX
Pointer → DMZ (Black)
Pointer → Size → Smallest (leftmost on slider)

Right click open area on Desktop → Change Desktop Background → Background
Colors → Solid color (#64A5CD)

After applying the above settings the desktop icon text should be white with a dark drop-shadow. This is the correct behavior.

Once the OS is restarted, the desktop icon text will become black (and very difficult to read given the background color). Going back to the Solid color menu and changing the solid desktop background color to any other similar color (adjust the green by one value for example) will cause the icon text to adjust to the correct white text again. 
If you then restart the OS again, the text will sadly revert back to the black text.

This bug is highly repeatable and happens every time.

This situation also affects the Start menu background color (makes it black instead of grey) but setting a custom color for the Start menu background worked as a work-around for that, but that might be related.

**Comment by NiceandGently** [comment]
I thought this was fixed, see
https://github.com/mate-desktop/caja/issues/105
https://github.com/mate-desktop/caja/commit/c5b6013dd50e5f7e888a28b86184db1102ca39ff
Can you please post the version of caja?

**Comment by NiceandGently** [comment]
Ok, the fix is in caja-1.8.2 release

**Comment by NiceandGently** [comment]
Don't use 1.9.x versions with mate-1.8.x !!!!!!!!
This will break your installation for shure.
Linuxmint needs updating caja to 1.8.2 .

**Comment by clefebvre** [comment]
Hi,

Version 1.8.2 is available in Linux Mint 17.1.

To upgrade from 17 to 17.1, please follow the steps described at http://blog.linuxmint.com/?p=2725

**Comment by BenFenner** [comment]
Thanks again for the useful information. I haven't done anything yet, so I will make sure to update to Mint 17.1 to get caja 1.8.2 installed.

I was not aware that major OS updates such as this were in a different section of the Update Manager. It is unintuitive and not highly discoverable. This is a stumbling block that could be avoided and also could have saved me a lot of time, but I realize this is not the place for that conversation.

Thank you for the help everyone, even if this is not exactly the right place for this issue.

**Comment by BenFenner** [comment]
Preliminary testing shows that updating to caja 1.8.2 via the Linux mint 17.1 update has fixed the issue with the icon text. The secondary issue with the start-menu background color still remains, so I'm going to assume that is also a caja issue and I'll create a new ticket there.

**Insert link to new issue here**

**Comment by NiceandGently** [comment]
@BenFenner 
The normal way to file out bug report is to file out them first to your distro bug reporting system.
Than the package maintainer can check if it is a distro issue or packaging issue.
The second step is to file out a report against upstream.

**Comment by NiceandGently** [comment]
PS: if you talk about a 'start-menu' issue than you mean mintmenu, right?
This package isn't maintained by mate, it's from linuxmint itself.

**Comment by BenFenner** [comment]
NiceandGently, thank you for the help. I see now that I should report my next issue with mintMenu. Sorry for the trouble.

As for filling out a bug report first with my distro reporting system, I did start out doing that, but it specifically said that if I was having trouble with the theme, or the way things looked, or the GUI in general that I should head over here to the MATE issue tracker.

Cheers!
