### ISSUE TITLE
Problems with tray icons in mate panel

### ISSUE THREAD

**Issue by philipzae** [mate-desktop/mate-icon-theme#18]
When resizing the mate panel in Linux Mint Mate from its default of 24 pixels in height, the network and volume icons dont look nice when the mate panel is between 25px and 31px. The network icon takes the icon 32px icon and scales it down, while the volume icon takes the 24px icon and scales it up.

![mint taskbar with gnome](https://cloud.githubusercontent.com/assets/4412114/6289758/d8513c14-b93b-11e4-899b-f2d732942354.png)
Top Row - 32px
Middle Row - 25px
Bottom - 24px

This issue has been reported in mate-panel and they suggested it also be posted here.
https://github.com/mate-desktop/mate-panel/issues/282

**Comment by NiceandGently** [comment]
won't fix
