### ISSUE TITLE
Menta miss a reference to missing icons

### ISSUE THREAD

**Issue by rapgro** [mate-desktop/mate-icon-theme#20]
Menta icons theme shows a default icon for lock, logoff and shutdown.
Mate theme that Menta inherits from does not show that issue.
Cinnamon sample: [http://www.picpaste.de/pics/882a2970ffc7277bf8993773ab0d198e.1463821408.png](url)
##

**Comment by flexiondotorg** [comment]
@rapgro The link you added is dead. Can you please update the issue without using Cinnamon as a reference :-)

**Comment by raveit65** [comment]
as far i recall we can close this.
