### ISSUE TITLE
gnome-mime-application-x-ms-dos-executable.png links to wrong (less specific) icon

### ISSUE THREAD

**Issue by glouglum** [mate-desktop/mate-icon-theme#21]
There are two executable icons in the Mate icon theme ...

**application-x-executable.png :**
![application-x-executable](https://cloud.githubusercontent.com/assets/25230617/22120101/2c3a389e-de4c-11e6-9c19-aaf1144b3893.png)

**application-x-ms-dos-executable.png :**
![application-x-ms-dos-executable](https://cloud.githubusercontent.com/assets/25230617/22120103/31c2202e-de4c-11e6-8311-44d7f0057144.png)

gnome-mime-application-x-ms-dos-executable.png should link the the second (more specific), but it's currently linking to the first (less specific).

**Comment by monsta** [comment]
Well, these symlinks are generated by `icon-naming-utils` tool. The wrong mapping is set in [legacy-icon-mapping.xml](https://sources.debian.org/src/icon-naming-utils/stretch/legacy-icon-mapping.xml/#L805) file. So, please file a bug report to the authors/maintainers of that tool.

**Comment by glouglum** [comment]
alright -- best i can tell, the place to report this is debian, so i've reported it here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888443
