### ISSUE TITLE
list of broken flags

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-icon-theme#22]
All Arabic and Spanish (Latin American) are displaying a stop sign instead of correct flags

![arabic](https://cloud.githubusercontent.com/assets/240100/24760773/d1a84d08-1b13-11e7-9dc8-540f0a313357.png)

Chinese is OK, but not selectable (But Chinese Tibetian and Chinese Uyghur are OK and selectable)

complete list:
<del>Afghani</del>
Algeria (wrong flag - more like a stop sign)
Argentina (wrong flag - more like a stop sign)
<del>Azerbaijani</del>
Bahrain (wrong flag - more like a stop sign)
<del>Belgium</del>
<del>Bosnia and Herzegovina</del>
<del>Botswana</del>
<del>Brunei Darusallam (Malay Jawi)</del>
Chile (wrong flag - more like a stop sign)
China (flags is visible, but not selectable)
Costa Rica - (wrong flag - more like a stop sign)
Cuba - (wrong flag - more like a stop sign)
Dominican Republic - (wrong flag - more like a stop sign)
Ecuador (wrong flag - more like a stop sign)
Egypt (wrong flag - more like a stop sign)
El Salvador (wrong flag - more like a stop sign)
<del>Estonian</del>
<del>Faroe Islands</del>
<del>Finland</del>
<del>Germany</del>
<del>Greece</del>
Guatemala (wrong flag - more like a stop sign)
<del>Guinea</del>
Haiti (wrong flag - more like a stop sign)
Honduras (wrong flag - more like a stop sign)
Jordan (wrong flag - more like a stop sign)
Kuwait (wrong flag - more like a stop sign)
<del>Kyrgyztan</del>
<del>Latvia</del>
Lebanon (wrong flag - more like a stop sign)
Libya (wrong flag - more like a stop sign)
<del>Mali (Bambara)</del>
Mauritania (wrong flag - more like a stop sign)
Mexico (wrong flag - more like a stop sign)
Morocco (wrong flag - more like a stop sign)
<del>Nepal</del>
<del>Netherlands</del>
Nicaragua (wrong flag - more like a stop sign)
Oman (wrong flag - more like a stop sign)
Palestine (wrong flag - more like a stop sign)
Panama - (wrong flag - more like a stop sign)
Paraguay (wrong flag - more like a stop sign)
Peru (wrong flag - more like a stop sign)
Puerto Rico (wrong flag - more like a stop sign)
Qatar (wrong flag - more like a stop sign)
<del>Romania</del>
Saudi Arabia (wrong flag - more like a stop sign)
<del>South Africa</del>
Sudan (wrong flag - more like a stop sign)
Syrian (wrong flag - more like a stop sign)
<del>Tanzania</del>
Tunisia (wrong flag - more like a stop sign)
UAE (wrong flag - more like a stop sign)
<del>United Kingdom</del>
<del>United States</del>
Uruguay (wrong flag - more like a stop sign)
Venezuela (wrong flag - more like a stop sign)
Western Sahara (wrong flag - more like a stop sign)
Yemen (wrong flag - more like a stop sign)

**Comment by raveit65** [comment]
fix for de, us and af
https://github.com/mate-desktop/mate-icon-theme/commit/8008ff2b29b85db3842e7661fb715357e7174d1b

**Comment by raveit65** [comment]
fix az, ba, be, bw and ee flags
https://github.com/mate-desktop/mate-icon-theme/commit/3d1c249a8a03a3b15f1c05ff1ad838b91674e3dd

**Comment by raveit65** [comment]
fix fi, fo, gn, gr, kg flags
https://github.com/mate-desktop/mate-icon-theme/commit/b425d405ce58e5e50239063158298aaafe51fdf4
fix gb, lv, ml, nl, ro, tz, za flags 
https://github.com/mate-desktop/mate-icon-theme/commit/1054e795523ae420c4ec1811a0bdf195fe79eb13
@willysr 
Can you please test updated flags.
Maybe i confused some :-)
Next step will be moving the flags to libmatkbd.
Maybe we can fix spanish and arabic countries in code there.

**Comment by willysr** [comment]
af -> fixed
de -> fixed
us -> fixed
az -> fixed
ba -> fixed
be -> fixed
bw -> fixed but probably the blue color doesn't match the national flag
ee -> fixed
fi -> fixed, but probably the blue color doesn't match the national flag
fo -> fixed
gn -> fixed, but probably the color doesn't match the national flag
gr -> fixed, but probably the blue color doesn't match the national flag
kg -> fixed

**Comment by willysr** [comment]
gb -> fixed
lv -> fixed
ml -> fixed
nl -> fixed
ro -> fixed
tz -> fixed
za -> fixed

**Comment by raveit65** [comment]
Sorry, but i used iso-flags.
... i don't want to spend my time to fix color proplems.
feel free to do that ;-)

**Comment by willysr** [comment]
ok, consider it fixed then :)
3 left: bn, np, and cn

**Comment by raveit65** [comment]
Hmm, those are working here

**Comment by willysr** [comment]
![bn](https://cloud.githubusercontent.com/assets/240100/25072968/d231e852-2305-11e7-878d-b2dedd39d015.png)

**Comment by willysr** [comment]
![np](https://cloud.githubusercontent.com/assets/240100/25072975/fdbe695a-2305-11e7-922d-33e0b092f36b.png)

**Comment by willysr** [comment]
I can't show screenshot for Chinese as i can select it, but i can't switch to it

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-icon-theme/commit/cadc96d892352570cbd2225b5151f92e1bc80342
Please try again
For some reasons i can't see the nice Malay flag in rhel7, seems like the locale is complete missing.

**Comment by willysr** [comment]
bn -> fixed
cn -> flag is fine, but i can't switch to Chinese keyboard layout. Do i need to install special fonts?
np -> fixed

**Comment by raveit65** [comment]
I dunno :-)

**Comment by raveit65** [comment]
I added the flags now to https://github.com/mate-desktop/libmatekbd/tree/dev-flags
Some work is needed there.
So i will close this one here and open a report in libmatekbd.
