### ISSUE TITLE
Missing icon named "preferences-system-time"

### ISSUE THREAD

**Issue by yetist** [mate-desktop/mate-icon-theme#37]
In this repo, it has symbolic icon, but no colored icon.

The symbolic icon: https://github.com/mate-desktop/mate-icon-theme/blob/master/mate/scalable/apps/preferences-system-time-symbolic.svg
![image](https://user-images.githubusercontent.com/665058/59700319-adde8f00-9225-11e9-958b-42ae447b7b0d.png)

There are two options for color icons:
- https://commons.wikimedia.org/wiki/File:Oxygen480-apps-preferences-system-time.svg 
![image](https://user-images.githubusercontent.com/665058/59700388-c8186d00-9225-11e9-96ef-f09d727f9afb.png)

- https://github.com/GNOME/gnome-control-center/blob/gnome-3-32/panels/datetime/icons/scalable/preferences-system-time.svg
![image](https://user-images.githubusercontent.com/665058/59700419-d797b600-9225-11e9-98f7-4fc92de0b7d9.png)

Which one is better? @mate-desktop/core-team

**Comment by yetist** [comment]
Related comment: https://github.com/mate-desktop/mate-control-center/pull/467#issuecomment-503186753

**Comment by rbuj** [comment]
+1 gnome icon: https://github.com/mate-desktop/mate-icon-theme/blob/master/src/clocks.svg
```shell
$ git grep clocks.svg
mate/16x16/actions/Makefile.am:appointment-new.png: ../../../src/clocks.svg
mate/16x16/actions/Makefile.am:document-open-recent.png: ../../../src/clocks.svg
mate/16x16/status/Makefile.am:appointment-missed.png: ../../../src/clocks.svg
mate/16x16/status/Makefile.am:appointment-soon.png: ../../../src/clocks.svg
mate/22x22/actions/Makefile.am:appointment-new.png: ../../../src/clocks.svg
mate/22x22/actions/Makefile.am:document-open-recent.png: ../../../src/clocks.svg
mate/22x22/status/Makefile.am:appointment-missed.png: ../../../src/clocks.svg
mate/22x22/status/Makefile.am:appointment-soon.png: ../../../src/clocks.svg
mate/24x24/actions/Makefile.am:appointment-new.png: ../../../src/clocks.svg
mate/24x24/actions/Makefile.am:document-open-recent.png: ../../../src/clocks.svg
mate/24x24/status/Makefile.am:appointment-missed.png: ../../../src/clocks.svg
mate/24x24/status/Makefile.am:appointment-soon.png: ../../../src/clocks.svg
mate/256x256/actions/Makefile.am:appointment-new.png: ../../../src/clocks.svg
mate/256x256/actions/Makefile.am:document-open-recent.png: ../../../src/clocks.svg
mate/256x256/status/Makefile.am:appointment-missed.png: ../../../src/clocks.svg
mate/256x256/status/Makefile.am:appointment-soon.png: ../../../src/clocks.svg
mate/32x32/actions/Makefile.am:appointment-new.png: ../../../src/clocks.svg
mate/32x32/actions/Makefile.am:document-open-recent.png: ../../../src/clocks.svg
mate/32x32/status/Makefile.am:appointment-missed.png: ../../../src/clocks.svg
mate/32x32/status/Makefile.am:appointment-soon.png: ../../../src/clocks.svg
mate/48x48/actions/Makefile.am:appointment-new.png: ../../../src/clocks.svg
mate/48x48/actions/Makefile.am:document-open-recent.png: ../../../src/clocks.svg
mate/48x48/status/Makefile.am:appointment-missed.png: ../../../src/clocks.svg
mate/48x48/status/Makefile.am:appointment-soon.png: ../../../src/clocks.svg
```

**Comment by raveit65** [comment]
I prefer oxygen icon or origin icon from mate-time-admin.
Why not respecting original authors choice?

**Comment by zhuyaliang** [comment]
@yetist I think the original icon is more beautiful

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-icon-theme/pull/38
This will add missing icons to mate-icon-theme. I chooses original icons with transparant background from this PR, which looks very nice.

**Comment by raveit65** [comment]
@zhuyaliang 
Do you have a .svg of your icon do complete PR with a colour preferences-system-time.svg in scalable folder of mate-icon-theme?

**Comment by zhuyaliang** [comment]
make the original icon ```mate-times-admin.png``` into ```references-system-time.svg``` ？Or something else

**Comment by raveit65** [comment]
You can't create a svg from a png. Pngs doesn't have different objects or layers like svgs.
Normally, there is a base svg icon which is use to create pngs in different sizes.
It's Ok if you don't have one.

**Comment by lukefromdc** [comment]
If you have a high resolution PNG icon, you can of course open it in Inkscape and save an SVG file of the same image. No doubt there will be some quality loss, but you do end up with an SVG icon from which PNG icons of many sizes could be derived. Trying to scale up from the original is still going to be blurry, as you lose data every time you rescale and there is no way to recreate data that never existed in the original file.

**Comment by raveit65** [comment]
> If you have a high resolution PNG icon, you can of course open it in Inkscape and save an SVG file of the same image......

This is only a fake svg, like a photo of an png inside a svg. Those fake svg doesn't have any objects.

**Comment by raveit65** [comment]
Mediocre result with icon from https://github.com/mate-desktop/mate-icon-theme/commit/37adf35b50e7bb7ebb8de5fb124e0f241218db76
![Bildschirmfoto zu 2019-06-20 10-13-12](https://user-images.githubusercontent.com/961604/59833085-9f879480-9345-11e9-87d5-47894655fd81.png)

**Comment by rbuj** [comment]
gnome icon + [desktop file](https://github.com/mate-desktop/mate-control-center/blob/test-time-admin-ui/capplets/time-admin/data/mate-time-admin.desktop.in) 

![Captura de pantalla a 2019-06-20 11-00-17](https://user-images.githubusercontent.com/10171411/59835844-c1374a80-934a-11e9-8ed2-0d639eec24a3.png)

**Comment by raveit65** [comment]
with Oxygen icon HIDPI
![Bildschirmfoto zu 2019-06-20 11-05-43](https://user-images.githubusercontent.com/961604/59836285-8386f180-934b-11e9-823d-cddfc4787f2a.png)

**Comment by raveit65** [comment]
New screenshot with using rsvg-convert to create pngs from oxyden svg.
![Bildschirmfoto zu 2019-06-20 11-37-36](https://user-images.githubusercontent.com/961604/59838920-13c73580-9350-11e9-9238-97e7d7819359.png)

**Comment by raveit65** [comment]
@mate-desktop/core-team 
Ok guys, please vote (like) which icon you prefer :)
Would be nice if we can finish that fast.

**Comment by rbuj** [comment]
> New screenshot with using rsvg-convert to create pngs from oxyden svg.

It looks better, icon seems larger and calendar contains more details.

**Comment by cwendling** [comment]
I think the GNOME icon fits better with the other ones.

**Comment by sc0w** [comment]
I have no problem with one or other :)

**Comment by yetist** [comment]
I like gnome's icon.

**Comment by lukefromdc** [comment]
The Oxygen icon is in my judgement to be preferred on grounds of
including thecalendar. The original we tried looked nicest to me but
apparently was never uploadedin a high enough resolution for hidpi or
maybe it's just lossy work in GIMP on my partto remove the bg.
Not a big deal, we can go with the Oxygen icon and the green lortion
goes well with defaultMATE themes. Remember that I was evaluating the
appearance in a darker GTK theme.
On 6/20/2019 at 9:31 AM, "ZenWalker"  wrote:

	I have no problem with one or other :)

**Comment by vkareh** [comment]
I prefer the GNOME icon

**Comment by monsta** [comment]
As this theme was originally forked from gnome-icon-theme, using gnome icon makes sense.

**Comment by raveit65** [comment]
I just added the gnome version of the icon to mate-icon-them.
Sadly the source .svg was only in 48x48px which i converted to 128x128 px.
So, https://github.com/mate-desktop/mate-control-center/pull/467 can be merged now.
